# Generated by Django 4.1.7 on 2023-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_rename_author_id_ads_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
