# Generated by Django 4.2 on 2023-05-09 18:49

import ads.validators.user_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[ads.validators.user_validators.check_birth_date]),
        ),
    ]
